"""remove container from process

Revision ID: 51aa0bb37894
Revises: 587fbe959d62
Create Date: 2025-09-17 12:18:47.933805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51aa0bb37894'
down_revision: Union[str, Sequence[str], None] = '587fbe959d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process', 'container')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('container', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
