"""allow same email for multiple users with different institutions

Revision ID: b27ad9a1e3c7
Revises: 51aa0bb37894
Create Date: 2025-09-19 11:30:26.937157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27ad9a1e3c7'
down_revision: Union[str, Sequence[str], None] = '51aa0bb37894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='user')
    op.drop_index(op.f('institution_id'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email', 'institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('institution_id'), 'user', ['institution_id'], unique=True)
    op.create_index(op.f('email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###
